### ISSUE TITLE
npm 安装后引入有问题哦，小哥哥

### ISSUE THREAD

**Issue by note520** [shayeLee/floway#1]
版本： "floway": "^1.2.1",
import {state} from "floway";
报错：
Failed to compile.

./node_modules/floway/dist/floway.js
Module not found: Error: Can't resolve './dispatch.js' in 'E:\xxx\xxx\node_modules\floway\dist';
是不是npm打包后有路径有问题？
目前解决办法：改成 import {state} from "floway/es/index";

**Comment by shayeLee** [comment]
已修复！
`npm update --save floway` 更新一下即可。
